name: Build mxe

on:
  workflow_call:
    inputs:
      MXE_VERSION:
        required: true
        type: string
      GCC_VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache MXE
        id: cache-mxe
        uses: actions/cache@v4
        with:
          path: /opt/mxe
          # NOTE: cache key includes libs suffix so cache gets rebuilt when adding packages
          key: ${{ runner.os }}-mxe-v${{ inputs.MXE_VERSION }}-gcc${{ inputs.GCC_VERSION }}-jsoncpp-sdl_net

      - name: Install MXE dependencies
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y autopoint gperf intltool libtool-bin lzip

      - name: Install MXE dependencies for newer MXE/GCC
        if: steps.cache-mxe.outputs.cache-hit != 'true' && inputs.GCC_VERSION > '11'
        run: |
          sudo apt-get install -y python3-mako

      - name: Install further dependencies for ACT
        if: ${{ env.ACT }}
        run: |
          sudo apt-get install -y p7zip-full bison flex ruby

      - name: Remove Python 3 and set Python 2 as default
        if: steps.cache-mxe.outputs.cache-hit != 'true' && inputs.GCC_VERSION <= '11'
        run: |
          sudo apt-get remove -y python3
          sudo apt-get install -y python2
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
          sudo update-alternatives --set python /usr/bin/python2

      - name: Set up MXE environment (Windows XP support)
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        run: |
          if [ ! -d /opt/mxe ]; then
            git clone https://github.com/mxe/mxe.git /opt/mxe
          fi
          cd /opt/mxe
          git checkout ${{ inputs.MXE_VERSION }}

          if [ "${{ inputs.MXE_VERSION }}" = "7e39b555dee5e906b24a44940055dc28d4056d23" ]; then
            sed -i 's/^$(PKG)_VERSION := .*/$(PKG)_VERSION := 8.0.3/' src/mingw-w64.mk
            sed -i 's/^$(PKG)_CHECKSUM := .*/$(PKG)_CHECKSUM := d702ef712c8f22035f81ddf6089542adf6bcb6ea669d4ebf4e311f87242882f0/' src/mingw-w64.mk
            cat src/mingw-w64.mk
          fi

          export MXE_PLUGIN_DIRS="$PWD/plugins/gcc${{ inputs.GCC_VERSION }}"

          # Added: sdl_net + jsoncpp
          make MXE_TARGETS=i686-w64-mingw32.static JOBS=$(nproc) \
            gcc cmake \
            sdl sdl_net sdl_gfx sdl_mixer sdl_image \
            yaml-cpp jsoncpp

      - name: Save MXE cache
        if: steps.cache-mxe.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: /opt/mxe
          key: ${{ runner.os }}-mxe-v${{ inputs.MXE_VERSION }}-gcc${{ inputs.GCC_VERSION }}-jsoncpp-sdl_net